package com.mycompany.graficadora;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Stroke;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author azoth
 */
public class PlanoLineal extends javax.swing.JFrame {

    private JPanel p;
    private int w;
    private int h;
    private int cont = 0;
    private int e; // Escala
    private Funcion f = new Funcion();
    
    public PlanoLineal() {
        initComponents();
    }
    
    public PlanoLineal (JPanel p) {
        this.p = p;
        this.w = p.getWidth();
        this.h = p.getHeight();
    }
    
    public void Dibujar(int cont) {
        Graphics2D g = (Graphics2D) p.getGraphics();
        
        // Limpiar si ya hay un plano previo
        if (cont > 1) {
            g.clearRect(0, 0, w, h);
        }
        
        
        
        for (int x1 = w / 2, x2 = w / 2 ; x1 < w; x1 += e, x2 -= e) {
            // Dibujar las lineas verticales del plano cartesiano
            g.drawLine(x1, 0, x1, h); // Desde el 0 hasta la derecha
            g.drawLine(x2, 0, x2, h); // Desde el 0 hasta la izquierda
        }
        
        for (int y1 = h/2, y2 = h/2; y1 < h; y1 += e, y2 -= e) {
            // Dibujar las lineas horizontales del plano cartesiano
            g.drawLine(0, y1, w, y1); // Desde el 0 hasta arriba
            g.drawLine(0, y2, w, y2); // Desde el 0 hasta abajo
        }
        
        // Hacer lineas en forma de puntos
        float[] dashingPattern = {2f, 2f};
        Stroke stroke = new BasicStroke(2f, BasicStroke.CAP_BUTT,
        BasicStroke.JOIN_MITER, 1.0f, dashingPattern, 2.0f);
        
        // Diferenciar lineas del medio
        g.setStroke(stroke);
        g.setColor(Color.blue);
        
        g.drawLine(w/2, 0, w/2, h);
        g.drawLine(0, h/2, w, h/2);
    }
    
    public void dibujarPunto (float x, float y) {
        Graphics2D g = (Graphics2D) p.getGraphics();
        // Coordenadas desde donde se dibujara el punto
        // Se le multiplica la escala para que el punto quede en la posicion correcta
        int pX = (int) (w/2 + x*e);
        int pY = (int) (h/2 - y*e);
        
        // Dibujar el punto
        // Se le resta el radio del ancho/alto para que el punto quede centrado
        g.fillOval(pX - 3, pY - 3, 6, 6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plano = new javax.swing.JPanel();
        graficarBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        aTxt = new javax.swing.JTextField();
        aLabel = new javax.swing.JLabel();
        bLabel = new javax.swing.JLabel();
        bTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Graficadora Lineal");

        plano.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        plano.setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout planoLayout = new javax.swing.GroupLayout(plano);
        plano.setLayout(planoLayout);
        planoLayout.setHorizontalGroup(
            planoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        planoLayout.setVerticalGroup(
            planoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        graficarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        graficarBtn.setText("GRAFICAR");
        graficarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                graficarBtnMouseClicked(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(204, 204, 204));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn.setText("VOLVER");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });

        aTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        aTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                aTxtKeyTyped(evt);
            }
        });

        aLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aLabel.setText("A:");

        bLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bLabel.setText("B:");

        bTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bTxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185)
                        .addComponent(graficarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(aLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(bLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bLabel)
                        .addComponent(aLabel))
                    .addComponent(aTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(graficarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void graficarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graficarBtnMouseClicked
        
        cont = cont + 1;
        
        PlanoLineal pL = new PlanoLineal(plano);
        pL.Dibujar(cont);
        
        String s1, s2;
        int a, b;

        
        s1 = aTxt.getText();
        s2 = bTxt.getText();
        
        if (s1.isEmpty()) {
            a = 0;
        }
        else {
            a = Integer.parseInt(s1); 

        }
        
        if (s2.isEmpty()) {
            b = 0;
        }
        else {
            b = Integer.parseInt(s2);
        }
        
        f.setLineal(a, b);
        f.DibujarLineal(pL);
    }//GEN-LAST:event_graficarBtnMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        this.setVisible(false);
        Graficadora g = new Graficadora();
        g.setVisible(true);
    }//GEN-LAST:event_backBtnMouseClicked

    private void bTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bTxtKeyTyped
        char validar = evt.getKeyChar();
        
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Solo ingrese números");
        }
    }//GEN-LAST:event_bTxtKeyTyped

    private void aTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aTxtKeyTyped
        char validar = evt.getKeyChar();
        
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Solo ingrese números");
        }
    }//GEN-LAST:event_aTxtKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aLabel;
    private javax.swing.JTextField aTxt;
    private javax.swing.JLabel bLabel;
    private javax.swing.JTextField bTxt;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton graficarBtn;
    private javax.swing.JPanel plano;
    // End of variables declaration//GEN-END:variables
}
